
# Hashed password for User
stdPwd = 'pbkdf2:sha256:260000$ufeCneSL7gRGeGGI$b70fa9915068ada3d0b2cfb66cf911538a0840908fac3729e9812980785cd386'


# Open and read PDF for Document testdata.
with open("configs/db/docs/no.ntnu inspera 81689313 82837975.pdf", "rb") as a:
    doc1 = a.read()

with open("configs/db/docs/18967_FULLTEXT.pdf", "rb") as a:
    doc2 = a.read()

with open("configs/db/docs/no.ntnu inspera 56692029 57168904.pdf", "rb") as a:
    doc3 = a.read()

with open("configs/db/docs/no.ntnu inspera 56803644 22271503.pdf", "rb") as a:
    doc4 = a.read()

with open("configs/db/docs/17656_FULLTEXT.pdf", "rb") as a:
    doc5 = a.read()

with open("configs/db/docs/18336_FULLTEXT.pdf", "rb") as a:
    doc6 = a.read()

# Open and read png Thumbnails for User testdata.
with open("configs/db/thumbnails/stian.png", "rb") as a:
    thumb1 = a.read()

with open("configs/db/thumbnails/haakon.png", "rb") as a:
    thumb2 = a.read()

with open("configs/db/thumbnails/tiger.png", "rb") as a:
    thumb3 = a.read()

with open("configs/db/thumbnails/musk.png", "rb") as a:
    thumb4 = a.read()

with open("configs/db/thumbnails/richard.png", "rb") as a:
    thumb5 = a.read()

with open("configs/db/thumbnails/bezos.png", "rb") as a:
    thumb6 = a.read()


# Title and Description for Document testdata.
tit1 = "Shorting in the technology sector of the Stock Market"
tit2 = "Selvkjørt er velkjørt? - En utforskende studie av automatiserte kjøretøys virkninger på trafikksikkerhet og kø"
tit3 = "Hvordan skape tillit til AI-systemer og motivere til korrekt bruk"
tit4 = "Kommunikasjon og Informasjonsflyt i Geografisk og Organisatorisk Distribuerte Vegplanleggingsprosjekter"
tit5 = "Trafikkavvikling med selvkjørende biler i blandet trafikk"
tit6 = "Mitigate Motion Sickness in Self-Driving Cars"

desc1 = "Ved bruk av Yahoo! Finance har vi hentet paneldata fra 371 teknologifirma oppført ved NASDAQ Composite Index, der vi studerer effekten som fire uavhengige variabler har på andelen aksjer som blir shortet. De fire uavhengige variablene vi valgte å studere er volum, markedsverdi, andelen aksjer holdt av eiere, og andelen aksjer holdt av institusjoner, og vi valgte å bruke short-raten som variabelen for å representere mengden aksjer shortet. En høy short-rate kan gjøre firmaer sårbare for short-klemmer, slik som hendelsen med GameStop i begynnelsen av 2021. Fra analysedelen finner vi en signifikant effekt på short-raten fra andelen aksjer holdt av eiere og andelen aksjer holdt av institusjoner. Vi finner også at volum og markedsverdien har en mer usikker effekt. Disse resultatene bruker vi til å drøfte GameStop-hendelsen, og for å se om det finnes en måte å forutsi, eller til og med unngå, short-klemmer på. By using Yahoo! Finance panel data of 371 technology firms listed at NASDAQ Composite Index, we are researching the effect of four independent variables on the shares. The four independent variables we chose are volume, market cap, shares held by insiders and shares held by institutions, and we chose to use short ratio as the variable for the share of shorted stocks. A high short ratio can make firms vulnerable for Short Squeeze incidents, like the incident with the GameStop stock in the beginning of 2021. From our analysis, we find a significant effect of the percentage of shares held by insiders and the percentage of shares held by institutions on short ratio. Volume and market cap have a more questionable effect. We use these results to discuss the GameStop incident and to see if there is a way to predict, or even avoid short squeezes to happen."
desc2 = "Konsekvensene av innføring av kommersielle automatiserte kjøretøy er omfattet av usikkerhet. Dette gjelder så vel usikkerhet med hensyn til selve teknologien, som hvilken effekt denne vil ha på trafikk, mobilitet og økonomi.Det første målet med oppgaven er å gi en oversikt over innholdet i begrepet Automatisk kjøretøy og hvilken innvirkning slike kjøretøy har på trafikksikkerhet og kødannelse. Det ble derfor foretatt en litteraturstudie om disse forholdene.Det andre målet med studien er å undersøke hvordan disse virkingene slår ut i norsk virkelighet. Funnene i litteraturen ble derfor overført til norske forhold og analysert i tre ulike scenarier, med tre ulike andeler automatiske kjøretøy av den totale kjøretøyflåten.Det siste målet er å undersøke om innføring av automatiserte kjøretøy kan bidra til å realisere regjeringens nullvisjon for døde og hardt skadde på norske veier.Resultatene av analysen viser en signifikant virkning både på trafikksikkerhet og køer i Norge. Den laveste raten av Automatiske kjøretøy (10 %) er beregnet til å medføre en reduksjon på 5 dødsfall og 39 alvorlige skader. 100 % automatiserte kjøretøy er beregnet til å medføre en reduksjon på 67 dødsfall og 450 alvorlige ulykker. Selv om automatiserte kjøretøy ikke alene vil kunne realisere nullvisjonen, viser modellen at man kan komme nær det konkrete etappemålet om maksimalt 350 drepte eller hardt skadde i 2030.De kombinerte kostnadsreduksjonene ved køreduksjon ble beregnet til minimum 4,5 mrd kroner ved lav andel automatiserte kjøretøy og maksimum 60,5 mrd ved full dekning."
desc3 = "Flere bedrifter har enten begynt eller vurderer å ta i bruk AI-systemer i organisasjonen deres. AI er en relativt ny teknologi, som er i konstant utvikling. Medier har rapportert ofte om AI, med både positive fremskritt i teknologi og negative artikler om hvordan AI, kommer til å ta over jobben din og gjøre deg arbeidsløs. På grunn av medier og hvordan mennesker er har det oppstått mistillit til denne typen systemer og mange er uvillige eller skeptiske til å ta i bruk denne formen for teknologi.Vi presenterer i denne rapporten hva som kreves av ledere og ansatte i bedrifter for å kunne skape tillit til AI-systemer og ta de i bruk på en riktig måte. Gjennom intervju får vi innblikk i hvordan en bedrift så på AI-systemet sitt basert på tillit og motivasjon.For å skape tillit og motivasjon til rett bruk av AI-system må bedrifter skape mestringsfølelse av bruk av systemet via god opplæring. Bedriften må implementere en helpdesk eller gode ledere som tar ansvar og støtter nye eller usikre brukere av systemet for minske graden av angst en ansatt har for å bruke systemet. Ledere i bedriften må ta i betraktning enkeltindividets emosjoner når det kommer til bruk av systemet og ta i bruk tiltak for at de opprettholder god tillit og motivasjon til AI-systemet. Bedriften må ha en god informasjonskanal ut i bedriften så alle er klar over hvorfor og hvordan de bruker systemet, og vise de ansatte både i praksis og opplæring hva slags nytte vi får fra det. Dersom en bedrift klarer å ta i bruk disse momentene kan de skape tillit til AI-systemene sine og motivere til bruk."
desc4 = "Det er i dagens samfunn og bedrifter store endringer i kommunikasjon og informasjonsflyt for å tilrettelegge for geografisk og organisatorisk distribuerte prosjekter. Denne rapporten tar for seg tre vegplanleggingsprosjekter hos Statens vegvesen som blir brukt til casestudie.Rapporten har en litterær gjennomgang av definisjoner på konsepter som informasjon, kommunikasjon og organisasjonsstruktur samt annet som ble vurdert som relevant for rapporten og dens problemstilling.Medlemmene av casestudie ble intervjuet og bedt om å føre en postjournal over all informasjon de mottok eller gav fra seg i en tidsperiode. Hensikten med dette var å kunne gjøre en kvalitativ og kvantitativ analyse av informasjonsflyten i prosjektet uavhengig av den enkeltes geografisk lokasjon eller organisatorisk posisjon.I den kvalitative analysen ble intervjuene analysert, sammenlignet og kommunikasjonskanaler identifisert, mens den kvantitative analysen brukte sosial nettverksanalyse for å finne frem til volumet av informasjonsflyten og hvem den gikk imellom.To viktige punkter dukket opp fra analysene om kommunikasjon og informasjonsflyten. Både at det ble antatt å være for mange og for få møter, og at det var mange unødvendige e-poster.Rapporten fortsetter med å foreslå å implementere en «pull» mekanisme støttet av status metadata knyttet til leveransene (filer) og på KanBan Board for å gjøre informasjon lettere tilgengelig.Det videre foreslåes at Kanban Board kombinert med korte disiplinerte «Stand-up» møter videre kan løse konsekvensene av en geografisk spredt og dynamisk organisasjon. Disse konsekvensen inkluderer fare for liten følelse av tilhørighet til prosjekter og manglende kunnskap om statusen til leveransene i prosjektet. Dette er en av årsakene til stor epost volum hos lederne og ønsker om flere møter hos enkelte."
desc5 = "Selvkjørende biler vil sannsynligvis være en del av trafikkbildet i flere land innen noen få år. Vil de bidra til bedre trafikkavvikling i trafikk blandet med konvensjonelle biler? Størstedelen av forskning om trafikkavvikling om selvkjørende biler er basert på datasimuleringer og ser ut til å være enig om at i trafikk med kun selvkjørende biler vil trafikkflyten bli bedre og trafikkvolumene vil bli høyere. Det er mer usikkert hvordan påvirkningen vil være i blandet trafikk, som ser ut til å være det mest realistiske scenarioet i nær fremtid.Selvkjørende biler vil benytte adaptiv cruisekontroll (ACC) eller lignende teknologi for å justere avstanden til bilen foran. Mange av dagens biler med ACC har ulike sikkerhetsinnstillinger for følgetiden som føreren selv kan velge mellom. Hvilken innstilling som velges har betydning for hvordan bilene påvirker trafikkavviklingen.Denne oppgaven prøver å svare på hvordan selvkjørende biler vil påvirke trafikkavviklingen i blandet trafikk og hvilken påvirkning ulike sikkerhetsinnstillinger for følgetid vil ha. For å gjøre dette har det blitt gjennomført et kvantitativt feltforsøk med registrering av metningsvolum i et signalregulert kryss. Forsøket ble gjort i reel rushtidstrafikk der fem forsøksbiler med ACC skulle etterligne selvkjørende biler. Forsøksbilene kjørte gjennom krysset som en del av trafikkstrømmen og hvor stor andel av strømmen som var forsøksbiler med ACC varierte. Halvparten av forsøket ble utført med største sikkerhetsavstand i innstillingene til forsøksbilenes ACC, mens den andre halvparten ble utført med minste sikkerhetsavstand.Resultatene fra forsøkene viser at forsøkskjøretøyene bidrar til dårligere trafikkavvikling med stor sikkerhetsavstand. For liten sikkerhetsavstand viser resultatene at de ikke bidrar til verken bedre eller dårligere trafikkavvikling.Sensorene og programvaren i forsøkskjøretøyene er ikke like avanserte som i selvkjørende biler. Med teknologisk utvikling kan sikkerhetsmarginene justeres ned, og dermed vil trolig selvkjørende biler bidra til bedre trafikkavvikling enn bilene som skulle etterligne dem i forsøket. Likevel ser det ikke ut til at bedre trafikkavvikling er et fokusområde for bilprodusentene, noe som gjør at resultatene for forsøket kan være realistiske. Det er vanskelig å forutsi hvordan utviklingen videre blir for selvkjørende biler. Hvor mye det fokuseres på trafikkavvikling i denne utviklingen kan være det som avgjør om selvkjørende biler vil bidra til bedre eller dårligere trafikkavvikling i blandet trafikk."
desc6 = "Motion sickness is an ancient problem lacking a silver bullet solution. Passengers are more prone to motion sickness than drivers, so as autonomous cars becomes the norm in the future, car sickness is projected to become a major problem. Motion sickness is expected to cause discomfort for hundreds of millions of people around the world. This does however give auto-manufactures an opportunity to differentiate themselves in the market if a good technical solution is developed. Motion sickness is quite complex, depending on sensory inputs and how the brain interprets them. Based on understanding how motion sickness occurs several strategies and techniques that can be useful against it is discussed. Validating the measures is currently done in an expensive and inaccurate manner, slowing down the research overall and makes smaller iterative improvements difficult. Autonomous cars allows for a new paradigm in motion sickness research, as driving patterns can be close to identical for participants. As test cars are driven with computer precision, research can be conducted in realistic scenarios instead of simulators which can't copy acceleration realistically, as well as causes simulator sickness which influences the results. If biometric data can be gathered in a non-intrusive manner and can be used to measure motion sickness in an accurate manner, data can be gathered cheaply and abundantly enough, to allow for a machine learning solution to replace current mathematical models of motion sickness."

